export const MYPROJECTS = [
  {
    id: 0,
    name: 'Nucamp website',
    image: '/assets/images/nucampsite.jpg',
    elevation: 1233,
    featured: false,
    type: 'bootcamp',
    focus: 'bootstrap, javascript, jsx, React and Redux',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi porttitor ultricies dolor, id volutpat arcu. I',
    link: 'https://github.com/chiyomi1104/React_Nucampsite',
  },
  {
    id: 1,
    name: 'Sake Subscription website ',
    image: '/assets/images/sakesite1.jpg',
    elevation: 877,
    featured: true,
    type: 'bootcamp',
    focus: 'bootstrap, javascript, jsx, React and Redux',
    description:
      'ipsum primis in faucibus. Vivamus maximus augue ut risus dictum, in tristique tellus convallis. Curabitur tristique ligula quam, vitae viverra nisl suscipit ut. Interdum et malesuada fames ac ',
    link: 'https://github.com/chiyomi1104/Sake-Website',
  },
  {
    id: 2,
    name: 'Nucamp website for mobile',
    image: '/assets/images/nucampsite-RN.jpg',
    elevation: 2901,
    featured: true,
    type: 'bootcamp',
    focus: 'bootstrap, javascript, jsx, React Native',
    description:
      'nas eget nulla ut sem convallis lacinia nec et metus. Nullam bibendum maximus dictum. Suspendisse potenti. Duis nec finibus lorem. Phasellus tincidunt lorem est, vel egestas sapien convallis sed. .',
    link: 'https://github.com/chiyomi1104/react-native',
  },
  {
    id: 3,
    name: 'Simple todo List ',
    image: '/assets/images/todolist4.jpg',
    elevation: 42,
    featured: true,
    type: 'personal',
    focus: 'bootstrap, javascript, jsx, React Native',
    description:
      'In finibus nulla vitae ipsum cursus, quis lacinia lectus tincidunt. Curabitur ultricies vel nisl sit amet lacinia. Mauris in porttitor nisl, ut consectetur nunc..',
    link: 'https://github.com/chiyomi1104/simpleTodoList',
  },
  {
    id: 4,
    name: 'Nucamp Server',
    image: '/assets/images/todolist4.jpg',
    elevation: 42,
    featured: true,
    type: 'bootcamp',
    focus: 'Node, Express, MongoDB',
    description:
      'In finibus nulla vitae ipsum cursus, quis lacinia lectus tincidunt. Curabitur ultricies vel nisl sit amet lacinia. Mauris in porttitor nisl, ut consectetur nunc..',
    link: 'https://github.com/chiyomi1104/NucampsiteServer_Node',
  },
  {
    id: 5,
    name: 'Covid Tracker',
    image: '/assets/images/covidtracker3.jpg',
    elevation: 42,
    featured: false,
    type: 'tutorials',
    focus: 'Node, Express, MongoDB',
    description:
      'In finibus nulla vitae ipsum cursus, quis lacinia lectus tincidunt. Curabitur ultricies vel nisl sit amet lacinia. Mauris in porttitor nisl, ut consectetur nunc..',
    link: 'https://github.com/chiyomi1104/covidtracker',
  },

  {
    id: 6,
    name: 'Over 50 Codepen Challengs',
    image: '/assets/images/codepenlogo.jpg',
    elevation: 42,
    featured: true,
    type: 'codepen',
    focus: 'html, css, bootstrap, javascript, react',
    link: 'https://codepen.io/Chi1104',
  },
  {
    id: 7,
    name: 'Personal projects',
    image: '/assets/images/todolist4.jpg',
    elevation: 42,
    featured: true,
    type: 'personal',
    focus: 'Node, Express, MongoDB',
    description:
      'In finibus nulla vitae ipsum cursus, quis lacinia lectus tincidunt. Curabitur ultricies vel nisl sit amet lacinia. Mauris in porttitor nisl, ut consectetur nunc..',
  },
  {
    id: 8,
    name: 'Personal projects2',
    image: '/assets/images/todolist4.jpg',
    elevation: 42,
    featured: true,
    type: 'personal',
    focus: 'Node, Express, MongoDB',
    description:
      'In finibus nulla vitae ipsum cursus, quis lacinia lectus tincidunt. Curabitur ultricies vel nisl sit amet lacinia. Mauris in porttitor nisl, ut consectetur nunc..',
  },
]
