export const MYPROJECTS = [
  {
    id: 0,
    name: 'Nucamp website',
    image: '/assets/images/nucampsite.jpg',
    featured: false,
    type: 'bootcamp',
    focus: 'bootstrap, javascript, jsx, React and Redux',
    description: 'Full-featured website with login modal, saving favorites, and commenting features. This demonstrates my React and Redux learning throughout the course. It is currently configured to load some content from a local database.',
    link: 'https://github.com/chiyomi1104/React_Nucampsite',
  },
  {
    id: 1,
    name: 'Sake Subscription website ',
    image: '/assets/images/sakesite1.jpg',
    featured: true,
    type: 'bootcamp',
    focus: 'bootstrap, javascript, jsx',
    description:
      'Bootstrap website for sake subscription business.',
    link: 'https://github.com/chiyomi1104/Sake-Website',
  },
  {
    id: 2,
    name: 'Nucamp website for mobile',
    image: '/assets/images/nucampsite-RN.jpg',
    featured: true,
    type: 'bootcamp',
    focus: 'bootstrap, javascript, jsx, React Native',
    description:
      'Remade the site with React Native. Same structure with Nucamp desktop website but featured with mobile-friendly behavior.',
    link: 'https://github.com/chiyomi1104/react-native',
  },
  {
    id: 3,
    name: 'Simple todo List ',
    image: '/assets/images/todolist4.jpg',
    featured: true,
    type: 'personal',
    focus: 'bootstrap, javascript, jsx, React Native',
    description:
      'React quick app to demonstrate my knowledge for React Native',
    link: 'https://github.com/chiyomi1104/simpleTodoList',
  },
  {
    id: 4,
    name: 'Nucamp Server',
    image: '/assets/images/server.png',
    featured: true,
    type: 'bootcamp',
    focus: 'Node, Express, MongoDB',
    description:
      'This Node.js Express Server uses MongoDB and Mongoose to provide resources for the NuCamp website mentioned earlier. The local server project was tested throughout development using PostMan.',
    link: 'https://github.com/chiyomi1104/NucampsiteServer_Node',
  },
  {
    id: 5,
    name: 'Covid Tracker',
    image: '/assets/images/covidtracker3.jpg',
    featured: false,
    type: 'tutorials',
    focus: 'Node, Express, MongoDB',
    description:
      'Covid tracker allows you to check how many people tested positive, recovered or died which data are scraped by API. It can be sorted by country.',
    link: 'https://github.com/chiyomi1104/covidtracker',
  },

  {
    id: 6,
    name: 'Over 50 Codepen Challengs',
    image: '/assets/images/codepenlogo.jpg',
    featured: true,
    type: 'codepen',
    description: 'Most of challenges are from the coding bootcamp. ',
    focus: 'html, css, bootstrap, javascript, react',
    link: 'https://codepen.io/Chi1104',
  },
  {
    id: 7,
    name: 'Portfolio site',
    image: '/assets/images/portfolio.jpg',
    featured: true,
    type: 'personal',
    focus: 'javascript, bootstrap, react',
    description: 'This website is which showcase my skills and projects.  ',
  },
  {
    id: 8,
    name: 'Movie exchanging social media',
    image: '/assets/images/wip.jpg',
    featured: true,
    type: 'personal',
    focus: 'javascript, react, bootstrap',
    description: 'Work in the progress',
  },
  {
    id: 9,
    name: 'Daiwa Massage',
    image: '/assets/images/daiwasite.jpg',
    featured: true,
    type: 'CMS',
    focus: 'wordpress, woocommerce',
    description:
      'Wordpress shopping site for high-end massage chair. Multisited for Hawaii and other regions and implemented several delivery options by zip code depends on the branchs ability.',
  },
  {
    id: 10,
    name: 'Honey Bunch Naturals',
    image: '/assets/images/hbnaturals.jpg',
    featured: true,
    type: 'CMS',
    focus: 'wordpress, woocommerce',
    description: 'Wordpress shopping site for New Zealand organic soaps and cosmetics. ',
  },
  {
    id: 10,
    name: 'Maxim Farm Wagyu Site',
    image: '/assets/images/maximfarm.jpg',
    featured: true,
    type: 'CMS',
    focus: 'Bigcommerce',
    description: 'Bigcommerce shopping site for Japanese A5 wagyu.',
  },
]
