export const MYPROJECTS = [
  {
    id: 0,
    name: 'Full-stack Nucamp website',
    image: '/assets/images/nucampsite.jpg',
    featured: false,
    type: 'Front end',
    focus: ['bootstrap', 'React', 'Redux', 'Node', 'Express', 'MongoDB'],
    description:
      'Full-featured website with login modal, saving favorites, and commenting features. This demonstrates my React and Redux learning throughout the course. It is currently configured to load some content from a local database. This Node.js Express Server uses MongoDB and Mongoose to provide resources for the NuCamp website mentioned earlier. The local server project was tested throughout development using PostMan.',
    github: 'https://github.com/chiyomi1104/React_Nucampsite',
    demo: '',
  },
  {
    id: 1,
    name: 'Sake subscription website ',
    image: '/assets/images/sakesite1.jpg',
    featured: true,
    type: 'Front end',
    focus: ['bootstrap', 'React'],
    description:
      'This is a sake subscription website made with react and bootstrap as one of the front-end development assignment from Nucamp.',
    github: 'https://github.com/chiyomi1104/Sake-Website',
    demo: 'https://sakit.netlify.app',
  },
  {
    id: 2,
    name: 'Nucamp website for mobile',
    image: '/assets/images/nucampsite-RN.jpg',
    featured: true,
    type: 'Mobile App',
    focus: ['bootstrap', 'React Native'],
    description:
      'Remade the site with React Native. Same structure with Nucamp desktop website but featured with mobile-friendly behavior.',
    github: 'https://github.com/chiyomi1104/react-native',
  },
  {
    id: 3,
    name: 'Simple todo List ',
    image: '/assets/images/todolist4.jpg',
    featured: true,
    type: 'Mobile App',
    focus: ['bootstrap', 'React Native'],
    description: 'This is the first app for myself to go over all the react Native system. ',
    github: 'https://github.com/chiyomi1104/simpleTodoList',
  },
 
  {
    id: 4,
    name: 'Covid Tracker',
    image: '/assets/images/covidtracker3.jpg',
    featured: false,
    type: 'Front end',
    focus: ['React', 'Material UI'],
    description:
      'Covid tracker allows you to check how many people tested positive, recovered or died which data are scraped by API. It can be sorted by country.',
    github: 'https://github.com/chiyomi1104/covidtracker',
    demo: 'https://covid19trackworld.netlify.app',
  },

  {
    id: 5,
    name: 'Over 50 Codepen Challengs',
    image: '/assets/images/codepenlogo.jpg',
    featured: true,
    type: 'codepen',
    description: 'Most of challenges are from the coding bootcamp. ',
    focus: ['HTML', 'CSS', 'Javascript', 'Bootstrap', 'React'],
    demo: 'https://codepen.io/Chi1104',
  },
  {
    id: 6,
    name: 'Portfolio site',
    image: '/assets/images/portfolio.jpg',
    featured: true,
    type: 'Front end',
    focus: ['React', 'Tailwind'],
    description: 'This website is which showcase my skills and projects.',
    github: 'https://github.com/sccala/portfolio',
    demo: 'https://chaseschung.netlify.app',
  },
  {
    id: 7,
    name: 'Anime memories social media',
    image: '/assets/images/wip.jpg',
    featured: true,
    type: 'Full stack',
    focus: ['Material UI', 'React', 'Redux', 'Express', 'Node', 'MongoDB Cloud Atlas'],
    description:
      'This is a full stack social media where people can share their memories about favorite anime scene. People can register their own account using Google Auth or email and password. Once they log in, they can create, read, update, delete their own posts. Also, users can react to others',
    github: 'https://github.com/sccala/memories_app',
    demo: 'https://memoriessocialapp.netlify.app',
  },
  {
    id: 8,
    name: 'Daiwa Massage',
    image: '/assets/images/daiwasite.jpg',
    featured: true,
    type: 'CMS',
    focus: ['WordPress', 'Woocommerce'],
    description:
      'Wordpress shopping site for high-end massage chair. Multisited for Hawaii and other regions and implemented several delivery options by zip code depends on the branchs ability.',
    demo: 'https://daiwamassage.com',
  },
  {
    id: 9,
    name: 'Honey Bunch Naturals',
    image: '/assets/images/hbnaturals.jpg',
    featured: true,
    type: 'CMS',
    focus: ['WordPress', 'Woocommerce', 'Photoshop', 'Illustrator'],
    description: 'Wordpress shopping site for New Zealand organic soaps and cosmetics. ',
    demo: 'https://honeybunchnaturals.us',
  },
  {
    id: 10,
    name: 'Maxim Farm Wagyu Site',
    image: '/assets/images/maximfarm.jpg',
    featured: true,
    type: 'CMS',
    focus: ['Bigcommerce'],
    description: 'Bigcommerce shopping site for Japanese A5 wagyu.',
    demo: 'https://maximfarm.com/',
  },
  {
    id: 11,
    name: 'Shadow Social Chat App',
    image: '/assets/images/wip.jpg',
    featured: true,
    type: 'Full stack',
    focus: ['Tailwind', 'React', 'Typescript', 'Redux', 'Express', 'Node', 'MongoDB Cloud Atlas'],
    description:
      'This is a social app for people who wants to whisper. Comments will be disappeared automatically after certain given time.',
    github: 'https://github.com/sccala/shadow_social',
    demo: 'https://socialchatapp.netlify.app',
  },
  {
    id: 12,
    name: 'Todo app - Frontend Mentor',
    image: '/assets/images/wip.jpg',
    featured: true,
    type: 'Front end',
    focus: ['Tailwind', 'React', 'Typescript', 'Redux'],
    description: 'This is a todo app to solidify my knowledge of redux and tailwind customize.',
    github: 'https://github.com/sccala/todo_redux',
    demo: 'https://todowredux.netlify.app',
  },
  {
    id: 14,
    name: 'Black Jack',
    image: '/assets/images/wip.jpg',
    featured: true,
    type: 'Front end',
    focus: ['Tailwind', 'React', 'Typescript', 'Redux'],
    description:
      'This is a web app to play black jack with a virtual dealer. I made this app for one of the Mintbean Hackathon, but also to solidify my knowledge for front-end development.',
    github: 'https://github.com/sccala/black_jack',
    demo: 'https://simplebj.netlify.app',
  },
]
