export const MYSKILLS = [
  {
    id: 0,
    name: 'Programming Languages',
    featured: false,
    focus: ['HTML', 'CSS', 'Javascript', 'Typescript', 'Python'],
  },
  {
    id: 1,
    name: 'Frameworks',
    featured: false,
    focus: [
      'React',
      'Vue',
      'Redux',
      'Sass',
      'Bootstrap',
      'MongoDB',
      'jQuery',
      'Express',
      'Node',
      'Firebase',
      'Material UI',
      'Tailwind',
      'Chakra UI',
    ],
  },
  {
    id: 2,
    name: 'Tools and Others',
    featured: false,
    focus: ['Illustrator', 'Photoshop', 'Indesign', 'XD', 'Figma', 'WordPress', 'Bigcommerce'],
  },
  {
    id: 3,
    name: 'Languages',
    featured: false,
    focus: ['Japanese', 'English'],
  },
]
